bar {
 swaybar_command waybar
}
exec foot --server
exec pipewire
exec mako
exec xdg-user-dirs-update
exec dbus-update-activation-environment --all DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway XDG_SESSION_TYPE=wayland
exec /bin/sh -c 'for a in /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 /usr/libexec/polkit-mate-authentication-agent-1 /usr/lib/polkit-mate/polkit-mate-authentication-agent-1; do [ -x "$a" ] && exec "$a"; done'
exec /bin/sh -c 'sleep 1; exec nm-applet --indicator'
exec swayidle -w \
 timeout 300 'swaylock -f -i ~/.config/walls/lock.png' \
 timeout 600 'swaymsg "output * dpms off"' \
 resume 'swaymsg "output * dpms on"' \
 before-sleep 'swaylock -f -i ~/.config/walls/lock.png'
exec $HOME/.config/custom_scripts/auto_start.sh
