title_align center
font pango:Noto Sans Bold 9
default_border pixel 3
default_floating_border normal 3
gaps inner 5
gaps outer 0
mouse_warping none
seat * hide_cursor 5000
focus_follows_mouse no
focus_wrapping no
client.focused $fg $fg $bg $fg $fg
client.unfocused $fg $bg $fg $uf $uf
client.focused_inactive $fg $fg $bg $uf $uf
client.urgent $ur $ur $bg $ur $ur
